#!/usr/bin/env bash
# installs nginx web server on server

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'server {
    listen 80;
    location / {
        echo "Hello World!";
    }
}' > /var/www/html/index.nginx-debian.html
service nginx start

