#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get -y  update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

service nginx restart
