#!/usr/bin/env bash

# Install and configure HAProxy to send traffic to web-01 and web-02 using a roundrobin algorithm
apt-get update
apt-get install -y haproxy
echo "frontend http_front
  bind *:80
  mode http
  default_backend http_back

backend http_back
  mode http
  balance roundrobin
  server web-01 118462-web-01:80 check
  server web-02 118462-web-02:80 check" >> /etc/haproxy/haproxy.cfg

# Ensure HAProxy can be managed via an init script
sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart HAProxy to apply changes
service haproxy restart

