#!/usr/bin/env bash

# Set nginx as the user in nginx.conf
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf

# Stop Apache if it's running
systemctl is-active --quiet apache2 && systemctl stop apache2
sudo -u nginx systemctl start nginx

